"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from .environment import allowed_hosts, database_configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

_default_weasyprint_dlls = (
    r'C:\msys64\mingw64\bin'
    if os.name == 'nt'
    else ''
)
WEASYPRINT_DLL_DIRECTORIES = os.environ.get(
    'WEASYPRINT_DLL_DIRECTORIES',
    _default_weasyprint_dlls,
)
if WEASYPRINT_DLL_DIRECTORIES:
    os.environ.setdefault(
        'WEASYPRINT_DLL_DIRECTORIES',
        WEASYPRINT_DLL_DIRECTORIES,
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

FRONTEND_BASE_URL = os.environ.get(
    'FRONTEND_BASE_URL',
    (
        'http://localhost:5173'
        if DEBUG
        else 'https://ecco-storefront.vercel.app'
    ),
).rstrip('/')
_configured_csrf_origins = os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    (
        'http://localhost:5173,http://127.0.0.1:5173'
        if DEBUG
        else ''
    ),
)
ALLOWED_HOSTS = allowed_hosts(
    os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1',
    ),
    os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''),
    f'{_configured_csrf_origins},{FRONTEND_BASE_URL}',
)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in f'{_configured_csrf_origins},{FRONTEND_BASE_URL}'.split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'catalog',
    'cart',
    'orders',
    'invoices',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL', '')
if DATABASE_URL:
    DATABASES = {
        'default': database_configuration(DATABASE_URL, debug=DEBUG)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'

CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')
if CLOUDINARY_URL:
    STORAGES = {
        'default': {
            'BACKEND': 'config.storage.PublicCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production-safe defaults activate when DJANGO_DEBUG is false. Deployments may
# override HSTS after confirming their HTTPS topology.
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_HSTS_SECONDS = int(
    os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0')
)

STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
PUBLISHED_SECRET_KEY = os.environ.get('PUBLISHED_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_GHS_TO_USD_RATE = os.environ.get('STRIPE_GHS_TO_USD_RATE', '0.065')
STRIPE_SUCCESS_URL = os.environ.get(
    'STRIPE_SUCCESS_URL',
    'http://localhost:5173/checkout/confirmation/{checkout_id}',
)
STRIPE_CANCEL_URL = os.environ.get(
    'STRIPE_CANCEL_URL',
    'http://localhost:5173/checkout?cancelled=1',
)
STORE_CURRENCY = os.environ.get('STORE_CURRENCY', 'GHS').upper()
STORE_TAX_RATE = os.environ.get('STORE_TAX_RATE', '0.075')
STORE_SHIPPING_FEE = os.environ.get('STORE_SHIPPING_FEE', '10.00')
STORE_FREE_SHIPPING_THRESHOLD = os.environ.get(
    'STORE_FREE_SHIPPING_THRESHOLD',
    '100.00',
)
INVOICE_COMPANY_NAME = os.environ.get('INVOICE_COMPANY_NAME', 'ECCO Store')
INVOICE_COMPANY_ADDRESS = os.environ.get(
    'INVOICE_COMPANY_ADDRESS',
    '123 Commerce Avenue, Accra, Ghana',
)
INVOICE_SUPPORT_EMAIL = os.environ.get(
    'INVOICE_SUPPORT_EMAIL',
    'support@example.com',
)
INVOICE_TAX_ID = os.environ.get('INVOICE_TAX_ID', '')

PASSWORD_RESET_TIMEOUT = int(
    os.environ.get('PASSWORD_RESET_TIMEOUT_SECONDS', '3600')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', '')
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET', '')
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID', '')
PAYPAL_API_BASE = os.environ.get(
    'PAYPAL_API_BASE', 'https://api-m.sandbox.paypal.com'
).rstrip('/')
PAYPAL_GHS_TO_USD_RATE = os.environ.get('PAYPAL_GHS_TO_USD_RATE', '0.065')
PAYMENT_SUCCESS_URL = os.environ.get(
    'PAYMENT_SUCCESS_URL',
    'http://127.0.0.1:5173/checkout/confirmation/{checkout_id}',
)
PAYMENT_CANCEL_URL = os.environ.get(
    'PAYMENT_CANCEL_URL', 'http://127.0.0.1:5173/checkout?cancelled=1'
)
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    (
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG
        else 'django.core.mail.backends.smtp.EmailBackend'
    ),
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in (
    '1',
    'true',
    'yes',
)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'ECCO Store <no-reply@example.com>',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': (
        'rest_framework.pagination.PageNumberPagination'
    ),
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'password_reset_request': '5/hour',
        'password_reset_confirm': '10/hour',
    },
}
