# Generated by Django 6.0.7 on 2026-08-12 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_stripe_transactions(apps, schema_editor):
    CheckoutAttempt = apps.get_model('orders', 'CheckoutAttempt')
    PaymentTransaction = apps.get_model('orders', 'PaymentTransaction')
    paid_statuses = {'paid', 'fulfilled', 'refund_pending', 'refunded', 'refund_failed'}
    for attempt in CheckoutAttempt.objects.exclude(stripe_session_id__isnull=True).iterator():
        status = 'paid' if attempt.status in paid_statuses else 'pending'
        if attempt.status == 'refunded':
            status = 'refunded'
        elif attempt.status in {'failed', 'expired'}:
            status = 'failed'
        PaymentTransaction.objects.create(
            checkout_id=attempt.pk,
            order_id=attempt.order_id,
            provider='stripe',
            method='card',
            provider_reference=attempt.stripe_payment_intent or attempt.stripe_session_id or '',
            status=status,
            store_amount=attempt.total,
            store_currency=attempt.currency,
            provider_amount=attempt.total,
            provider_currency=attempt.currency,
            exchange_rate=1,
            refunded_amount=attempt.total if status == 'refunded' else 0,
            paid_at=attempt.updated_at if status in {'paid', 'refunded'} else None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancelled_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('paypal', 'PayPal')], max_length=16)),
                ('method', models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile money'), ('bank_transfer', 'Bank transfer')], max_length=24)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('card_brand', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='initialized', max_length=16)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('store_currency', models.CharField(max_length=3)),
                ('provider_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('provider_refund_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='orders.checkoutattempt')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('store_amount__gte', 0)), name='payment_store_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('provider_amount__gte', 0)), name='payment_provider_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='payment_exchange_rate_positive')],
            },
        ),
        migrations.RunPython(backfill_stripe_transactions, migrations.RunPython.noop),
    ]
