# Generated by Django 6.0.7 on 2026-08-12 01:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_minimum_stock_quantity_purchaseorder_and_more'),
        ('orders', '0007_shippingmethod_shippingzone_order_courier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('masked_code', models.CharField(editable=False, max_length=24)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='GHS', editable=False, max_length=3)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('redeemed', 'Redeemed')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)])),
                ('scope', models.CharField(choices=[('store', 'Entire store'), ('categories', 'Selected categories'), ('products', 'Selected products')], max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-starts_at', 'name'),
            },
        ),
        migrations.AddField(
            model_name='checkoutattempt',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='checkoutattempt',
            name='gift_card_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='checkoutattempt',
            name='gift_card_masked',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='checkoutattempt',
            name='gift_card_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutattempt',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='checkoutattempt',
            name='promotion_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_masked',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='coupon_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_subtotal__gte', 0)), name='coupon_minimum_nonnegative'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_gift_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkoutattempt',
            name='gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_attempts', to='orders.giftcard'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_transactions', to='orders.checkoutattempt'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.giftcard'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(condition=models.Q(('initial_balance__gt', 0)), name='gift_card_initial_positive'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0)), name='gift_card_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance__gte', 0)), name='gift_card_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='giftcardtransaction',
            constraint=models.UniqueConstraint(fields=('checkout', 'kind'), name='unique_gift_card_checkout_kind'),
        ),
        migrations.AddConstraint(
            model_name='giftcardtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='gift_card_transaction_positive'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='promotion_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='promotion_dates_ordered'),
        ),
    ]
