# Generated by Django 6.0.7 on 2026-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_giftcard_giftcardtransaction_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile money'), ('bank_transfer', 'Bank transfer'), ('gift_card', 'Gift card')], max_length=24),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('paypal', 'PayPal'), ('store_credit', 'Store credit')], max_length=16),
        ),
    ]
