# Generated by Django 6.0.7 on 2026-08-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_coupon_value_alter_giftcard_initial_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='kind',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('redeemed', 'Redeemed'), ('restored', 'Restored after refund')], max_length=12),
        ),
    ]
