# Generated by Django 6.0.7 on 2026-08-12 02:17

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def create_store_configuration(apps, schema_editor):
    StoreConfiguration = apps.get_model('orders', 'StoreConfiguration')
    StoreConfiguration.objects.get_or_create(pk=1, defaults={
        'store_name': getattr(settings, 'INVOICE_COMPANY_NAME', 'ECCO Store'),
        'address': getattr(settings, 'INVOICE_COMPANY_ADDRESS', ''),
        'email': getattr(settings, 'INVOICE_SUPPORT_EMAIL', ''),
        'tax_rate': Decimal(getattr(settings, 'STORE_TAX_RATE', '0.075')),
    })


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_giftcardtransaction_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='ECCO Store', max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_label', models.CharField(choices=[('vat', 'VAT'), ('gst', 'GST'), ('sales_tax', 'Sales Tax'), ('none', 'No Tax')], default='vat', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=5, default=Decimal('0.075'), max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('send_order_emails', models.BooleanField(default=True)),
                ('send_invoice_emails', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'store configuration',
                'permissions': (('manage_store_settings', 'Can manage store settings'),),
            },
        ),
        migrations.RunPython(create_store_configuration, migrations.RunPython.noop),
    ]
