from django.urls import path

from .views import (
    CheckoutQuoteView,
    CheckoutSessionView,
    CheckoutStatusView,
    OrderDetailView,
    OrderListView,
    CustomerReturnRequestView,
    StaffOrderEmailView,
    StaffOrderRefundView,
    StaffRefundListView,
    StaffReturnDetailView,
    StaffReturnListView,
    StaffAnalyticsView,
    StaffAnalyticsSocketTicketView,
    HostedPaymentView,
    PaymentMethodListView,
    StaffPaymentMethodView,
    StaffPaymentReportView,
    StaffPaymentTransactionListView,
    PaystackWebhookView,
    PayPalWebhookView,
    StaffShippingMethodViewSet,
    StaffShippingOrderListView,
    StaffShippingRateViewSet,
    StaffShippingZoneViewSet,
    StaffCouponViewSet,
    StaffGiftCardTransactionListView,
    StaffGiftCardViewSet,
    StaffPromotionViewSet,
    StaffStoreConfigurationView,
    StaffSystemSettingsView,
    StripeWebhookView,
)


urlpatterns = [
    path('staff/settings/store/', StaffStoreConfigurationView.as_view(), name='staff-store-settings'),
    path('staff/settings/system/', StaffSystemSettingsView.as_view(), name='staff-system-settings'),
    path('staff/analytics/', StaffAnalyticsView.as_view(), name='staff-analytics'),
    path('staff/analytics/socket-ticket/', StaffAnalyticsSocketTicketView.as_view(), name='staff-analytics-socket-ticket'),
    path('staff/payments/transactions/', StaffPaymentTransactionListView.as_view(), name='staff-payment-transactions'),
    path('staff/payments/methods/', StaffPaymentMethodView.as_view(), name='staff-payment-methods'),
    path('staff/payments/refunds/', StaffRefundListView.as_view(), name='staff-payment-refunds'),
    path('staff/payments/reports/', StaffPaymentReportView.as_view(), name='staff-payment-reports'),
    path('staff/shipping/orders/', StaffShippingOrderListView.as_view(), name='staff-shipping-orders'),
    path('staff/shipping/methods/', StaffShippingMethodViewSet.as_view({'get': 'list', 'post': 'create'}), name='staff-shipping-method-list'),
    path('staff/shipping/methods/<int:pk>/', StaffShippingMethodViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'}), name='staff-shipping-method-detail'),
    path('staff/shipping/zones/', StaffShippingZoneViewSet.as_view({'get': 'list', 'post': 'create'}), name='staff-shipping-zone-list'),
    path('staff/shipping/zones/<int:pk>/', StaffShippingZoneViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'}), name='staff-shipping-zone-detail'),
    path('staff/shipping/rates/', StaffShippingRateViewSet.as_view({'get': 'list', 'post': 'create'}), name='staff-shipping-rate-list'),
    path('staff/shipping/rates/<int:pk>/', StaffShippingRateViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'}), name='staff-shipping-rate-detail'),
    path('staff/discounts/coupons/', StaffCouponViewSet.as_view({'get': 'list', 'post': 'create'}), name='staff-coupon-list'),
    path('staff/discounts/coupons/<int:pk>/', StaffCouponViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'}), name='staff-coupon-detail'),
    path('staff/discounts/promotions/', StaffPromotionViewSet.as_view({'get': 'list', 'post': 'create'}), name='staff-promotion-list'),
    path('staff/discounts/promotions/<int:pk>/', StaffPromotionViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'}), name='staff-promotion-detail'),
    path('staff/discounts/gift-cards/', StaffGiftCardViewSet.as_view({'get': 'list', 'post': 'create'}), name='staff-gift-card-list'),
    path('staff/discounts/gift-cards/<int:pk>/', StaffGiftCardViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update'}), name='staff-gift-card-detail'),
    path('staff/discounts/gift-cards/<int:pk>/transactions/', StaffGiftCardTransactionListView.as_view(), name='staff-gift-card-transactions'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/returns/', CustomerReturnRequestView.as_view(), name='customer-return-request'),
    path('staff/returns/', StaffReturnListView.as_view(), name='staff-return-list'),
    path('staff/returns/<int:pk>/', StaffReturnDetailView.as_view(), name='staff-return-detail'),
    path('staff/refunds/', StaffRefundListView.as_view(), name='staff-refund-list'),
    path('staff/orders/<int:pk>/refund/', StaffOrderRefundView.as_view(), name='staff-order-refund'),
    path('staff/orders/<int:pk>/send-email/', StaffOrderEmailView.as_view(), name='staff-order-email'),
    path('checkout/quote/', CheckoutQuoteView.as_view(), name='checkout-quote'),
    path('checkout/payment-methods/', PaymentMethodListView.as_view(), name='payment-methods'),
    path('checkout/payments/', HostedPaymentView.as_view(), name='hosted-payment'),
    path(
        'checkout/sessions/',
        CheckoutSessionView.as_view(),
        name='checkout-session',
    ),
    path(
        'checkout/sessions/<uuid:pk>/',
        CheckoutStatusView.as_view(),
        name='checkout-status',
    ),
    path(
        'payments/stripe/webhook/',
        StripeWebhookView.as_view(),
        name='stripe-webhook',
    ),
    path('payments/paystack/webhook/', PaystackWebhookView.as_view(), name='paystack-webhook'),
    path('payments/paypal/webhook/', PayPalWebhookView.as_view(), name='paypal-webhook'),
]
