import { useEffect, useState } from 'react';
import { Link, Navigate, useSearchParams } from 'react-router-dom';
import { FiCheckCircle, FiCreditCard, FiLock, FiMail, FiSettings, FiShield, FiTruck, FiUsers } from 'react-icons/fi';
import { settingsApi } from '../api/services';
import { fieldErrors } from '../api/client';
import { Alert, Button, Field, Loader } from '../components/ui';
import { useAuth } from '../hooks/useAuth';
import { useToast } from '../hooks/useToast';

const TABS = [['store', 'Store'], ['team', 'Users & roles'], ['system', 'System']];

export function SettingsPage() {
    const { user } = useAuth();
    const [params, setParams] = useSearchParams();
    const [system, setSystem] = useState(null);
    const tab = params.get('view') || 'store';
    useEffect(() => { if (user?.can_manage_settings) settingsApi.system().then(setSystem).catch(() => {}); }, [user]);
    if (!user?.can_manage_settings) return <Navigate to="/account" replace/>;
    const tabs = TABS.filter(([value]) => value !== 'team' || system?.can_manage_users);
    return <div className="container page settings-page"><div className="page-heading"><div><p className="eyebrow">Store configuration</p><h1>Settings</h1><p>Manage your storefront, staff access, commerce defaults, and service status.</p></div></div><nav className="settings-tabs" aria-label="Settings sections">{tabs.map(([value, label]) => <button type="button" key={value} className={tab === value ? 'active' : ''} onClick={() => setParams(value === 'store' ? {} : { view: value })}>{label}</button>)}</nav>{tab === 'store' && <StoreSettings/>}{tab === 'team' && system?.can_manage_users && <TeamSettings/>}{tab === 'system' && <SystemSettings system={system}/>}</div>;
}

function StoreSettings() {
    const { notify } = useToast(); const [data, setData] = useState(null); const [logo, setLogo] = useState(null); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false);
    useEffect(() => { settingsApi.store().then(setData).catch((reason) => setErrors({ detail: reason.message })); }, []);
    if (!data) return errors.detail ? <Alert>{errors.detail}</Alert> : <Loader label="Loading store settings"/>;
    const change = (field, value) => setData({ ...data, [field]: value });
    const submit = async (event) => { event.preventDefault(); setSaving(true); setErrors({}); const body = new FormData(); ['store_name', 'address', 'phone', 'email', 'tax_label', 'tax_rate', 'send_order_emails', 'send_invoice_emails'].forEach((key) => body.append(key, data[key])); if (logo) body.append('logo', logo); try { setData(await settingsApi.updateStore(body)); setLogo(null); notify('Store settings saved.', 'success'); } catch (reason) { setErrors(fieldErrors(reason.data)); } finally { setSaving(false); } };
    return <form className="settings-grid" onSubmit={submit}><section className="settings-card settings-card--wide"><header><FiSettings/><div><h2>Store settings</h2><p>Public identity and contact information.</p></div></header>{errors.detail && <Alert>{errors.detail}</Alert>}<div className="settings-form-grid"><Field label="Store name" name="store-name" required value={data.store_name} error={errors.store_name} onChange={(e) => change('store_name', e.target.value)}/><Field label="Store email" name="store-email" type="email" value={data.email} error={errors.email} onChange={(e) => change('email', e.target.value)}/><Field label="Phone" name="store-phone" value={data.phone} error={errors.phone} onChange={(e) => change('phone', e.target.value)}/><Field label="Address" name="store-address" value={data.address} error={errors.address} onChange={(e) => change('address', e.target.value)}/><label className="field"><span>Store logo</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setLogo(e.target.files?.[0] || null)}/>{data.logo && <small>Current logo: <a href={data.logo} target="_blank" rel="noreferrer">view image</a></small>}{errors.logo && <small className="field__error">{errors.logo}</small>}</label></div></section><section className="settings-card"><header><FiCreditCard/><div><h2>Tax settings</h2><p>Applied to new checkout calculations.</p></div></header><label className="field"><span>Tax type</span><select value={data.tax_label} onChange={(e) => change('tax_label', e.target.value)}><option value="vat">VAT</option><option value="gst">GST</option><option value="sales_tax">Sales Tax</option><option value="none">No tax</option></select></label><Field label="Tax rate (0–1)" name="tax-rate" type="number" min="0" max="1" step="0.00001" value={data.tax_rate} error={errors.tax_rate} onChange={(e) => change('tax_rate', e.target.value)}/></section><section className="settings-card"><header><FiMail/><div><h2>Email notifications</h2><p>Choose automatic customer messages.</p></div></header><Toggle label="Order confirmations and status emails" checked={data.send_order_emails} onChange={(value) => change('send_order_emails', value)}/><Toggle label="Invoice emails" checked={data.send_invoice_emails} onChange={(value) => change('send_invoice_emails', value)}/></section><footer className="settings-save"><Button type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save settings'}</Button></footer></form>;
}

function TeamSettings() {
    const { notify } = useToast(); const [users, setUsers] = useState(null); const [roles, setRoles] = useState(null); const [permissions, setPermissions] = useState([]); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(null); const [invite, setInvite] = useState({ username: '', email: '', role_ids: [] });
    const load = () => Promise.all([settingsApi.users(), settingsApi.roles(), settingsApi.permissions()]).then(([u, r, p]) => { setUsers(u.results || u); setRoles(r.results || r); setPermissions(p.results); }).catch((reason) => setError(reason.message));
    useEffect(() => { void load(); }, []);
    if (!users || !roles) return error ? <Alert>{error}</Alert> : <Loader label="Loading staff and roles"/>;
    const createUser = async (event) => { event.preventDefault(); setError(''); try { const result = await settingsApi.createUser(invite); notify(result.invitation_sent ? 'Staff invitation sent.' : 'Staff created, but the invitation email failed.', result.invitation_sent ? 'success' : 'error'); setInvite({ username: '', email: '', role_ids: [] }); await load(); } catch (reason) { setError(reason.message); } };
    const toggleUser = (member) => setConfirm({ title: `${member.is_active ? 'Deactivate' : 'Activate'} ${member.username}?`, message: member.is_active ? 'They will no longer be able to sign in.' : 'They will regain staff access.', action: async () => { await settingsApi.updateUser(member.id, { is_active: !member.is_active }); await load(); } });
    const changeRoles = async (member, options) => { const role_ids = [...options].filter((item) => item.selected).map((item) => Number(item.value)); try { await settingsApi.updateUser(member.id, { role_ids }); notify('Staff roles updated.', 'success'); await load(); } catch (reason) { setError(reason.message); } };
    return <div className="settings-stack">{error && <Alert>{error}</Alert>}<section className="settings-card settings-card--wide"><header><FiUsers/><div><h2>Staff and administrators</h2><p>Invite staff, assign roles, and control account access.</p></div></header><form className="staff-invite-form" onSubmit={createUser}><Field label="Username" name="invite-username" required value={invite.username} onChange={(e) => setInvite({ ...invite, username: e.target.value })}/><Field label="Email" name="invite-email" type="email" required value={invite.email} onChange={(e) => setInvite({ ...invite, email: e.target.value })}/><label className="field"><span>Initial roles</span><select multiple value={invite.role_ids.map(String)} onChange={(e) => setInvite({ ...invite, role_ids: [...e.target.selectedOptions].map((item) => Number(item.value)) })}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><Button type="submit">Send invitation</Button></form><div className="staff-product-table-wrap"><table className="staff-product-table"><thead><tr><th>User</th><th>Type</th><th>Roles</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map((member) => <tr key={member.id}><th>{member.username}<small>{member.email}</small></th><td>{member.is_superuser ? 'Administrator' : 'Staff'}</td><td>{member.is_superuser ? 'Full access' : <select multiple value={member.roles.map((role) => String(role.id))} onChange={(e) => void changeRoles(member, e.target.options)}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select>}</td><td><span className={`catalog-state catalog-state--${member.is_active ? 'active' : 'inactive'}`}>{member.is_active ? 'Active' : 'Inactive'}</span></td><td>{!member.is_superuser && <button type="button" className={member.is_active ? 'danger-link' : 'text-link'} onClick={() => toggleUser(member)}>{member.is_active ? 'Deactivate' : 'Activate'}</button>}</td></tr>)}</tbody></table></div></section><RoleEditor roles={roles} permissions={permissions} reload={load} setError={setError} confirm={setConfirm}/>{confirm && <ConfirmDialog {...confirm} onClose={() => setConfirm(null)} notify={notify}/>}</div>;
}

function RoleEditor({ roles, permissions, reload, setError, confirm }) {
    const { notify } = useToast(); const [name, setName] = useState(''); const [selected, setSelected] = useState([]);
    const save = async (event) => { event.preventDefault(); try { await settingsApi.createRole({ name, permission_ids: selected }); setName(''); setSelected([]); notify('Role created.', 'success'); await reload(); } catch (reason) { setError(reason.message); } };
    const remove = (role) => confirm({ title: `Delete ${role.name}?`, message: 'Only empty roles can be deleted.', action: async () => { await settingsApi.deleteRole(role.id); await reload(); } });
    return <section className="settings-card settings-card--wide"><header><FiShield/><div><h2>Roles and permissions</h2><p>Only approved ecommerce permissions can be assigned.</p></div></header><form className="role-create-form" onSubmit={save}><Field label="Role name" name="role-name" required value={name} onChange={(e) => setName(e.target.value)}/><div className="permission-grid">{permissions.map((permission) => <label key={permission.id}><input type="checkbox" checked={selected.includes(permission.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, permission.id] : selected.filter((id) => id !== permission.id))}/><span>{permission.name}</span></label>)}</div><Button type="submit">Create role</Button></form><div className="role-list">{roles.map((role) => <RoleRow key={role.id} role={role} permissions={permissions} reload={reload} setError={setError} remove={remove}/>)}</div></section>;
}

function RoleRow({ role, permissions, reload, setError, remove }) {
    const { notify } = useToast(); const [editing, setEditing] = useState(false); const [name, setName] = useState(role.name); const [selected, setSelected] = useState(role.permissions.map((item) => item.id));
    const save = async () => { try { await settingsApi.updateRole(role.id, { name, permission_ids: selected }); notify('Role updated.', 'success'); setEditing(false); await reload(); } catch (reason) { setError(reason.message); } };
    return <article className={editing ? 'is-editing' : ''}><div><strong>{role.name}</strong><small>{role.member_count} staff · {role.permissions.length} permissions</small></div><div className="role-list__actions"><button type="button" className="text-link" onClick={() => setEditing(!editing)}>Edit</button><button type="button" className="danger-link" onClick={() => remove(role)}>Delete</button></div>{editing && <div className="role-inline-editor"><Field label="Role name" name={`role-${role.id}`} value={name} onChange={(e) => setName(e.target.value)}/><div className="permission-grid">{permissions.map((permission) => <label key={permission.id}><input type="checkbox" checked={selected.includes(permission.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, permission.id] : selected.filter((id) => id !== permission.id))}/>{permission.name}</label>)}</div><Button type="button" onClick={() => void save()}>Save role</Button></div>}</article>;
}

function SystemSettings({ system }) {
    if (!system) return <Loader label="Loading system configuration"/>;
    const unavailable = ['Two-factor authentication', 'Login history', 'API keys', 'Backup & restore', 'SMS alerts', 'Push notifications', 'DHL / FedEx', 'QuickBooks / Xero', 'Mailchimp'];
    return <div className="settings-grid"><section className="settings-card settings-card--wide"><header><FiCreditCard/><div><h2>Payment settings</h2><p>Credentials remain protected in the server environment.</p></div></header><div className="settings-status-grid">{system.payments.map((item) => <article key={`${item.provider}-${item.label}`}><span className={item.configured ? 'is-ready' : ''}><FiCheckCircle/></span><div><strong>{item.label}</strong><small>{item.configured ? 'Configured' : 'Not configured'}</small></div></article>)}</div><p className="settings-note">Store currency: <strong>{system.store_currency}</strong>. Secret keys are never exposed here.</p></section><section className="settings-card"><header><FiMail/><div><h2>Email settings</h2><p>Safe SMTP connection details.</p></div></header><dl className="settings-details"><div><dt>Backend</dt><dd>{system.email.backend}</dd></div><div><dt>Host</dt><dd>{system.email.host}:{system.email.port}</dd></div><div><dt>TLS</dt><dd>{system.email.tls ? 'Enabled' : 'Disabled'}</dd></div><div><dt>Credentials</dt><dd>{system.email.configured ? 'Configured' : 'Missing'}</dd></div></dl></section><section className="settings-card"><header><FiTruck/><div><h2>Shipping settings</h2><p>Methods, delivery zones, and rates.</p></div></header><Link className="button button--secondary" to="/staff/shipping">Manage shipping</Link></section><section className="settings-card settings-card--wide"><header><FiLock/><div><h2>Security and integrations</h2><p>Capabilities that need dedicated secure infrastructure are not simulated.</p></div></header><div className="unavailable-grid">{unavailable.map((item) => <div key={item}><strong>{item}</strong><span>Unavailable</span></div>)}</div><p className="settings-note">Password policy: {system.security.password_validators.length} validators · Session timeout: {Math.round(system.security.session_timeout_seconds / 3600)} hours.</p></section></div>;
}

function Toggle({ label, checked, onChange }) { return <label className="settings-toggle"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)}/><span><strong>{label}</strong><small>{checked ? 'Enabled' : 'Disabled'}</small></span></label>; }
function ConfirmDialog({ title, message, action, onClose, notify }) { const [busy, setBusy] = useState(false); const run = async () => { setBusy(true); try { await action(); notify('Change completed.', 'success'); onClose(); } catch (reason) { notify(reason.message, 'error'); setBusy(false); } }; return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget && !busy) onClose(); }}><section className="confirm-modal" role="dialog" aria-modal="true"><p className="eyebrow">Confirm change</p><h2>{title}</h2><p>{message}</p><div className="confirm-modal__actions"><Button variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button variant="danger" disabled={busy} onClick={() => void run()}>{busy ? 'Working…' : 'Confirm'}</Button></div></section></div>; }
