import { useCallback, useEffect, useState } from 'react';
import { Link, Navigate, useSearchParams } from 'react-router-dom';
import { shippingApi } from '../api/services';
import { Alert, Button, EmptyState, Loader, Pagination } from '../components/ui';
import { useAuth } from '../hooks/useAuth';
import { useToast } from '../hooks/useToast';
import { formatPrice } from '../utils/format';

const TABS = [['orders', 'Shipping orders'], ['methods', 'Shipping methods'], ['tracking', 'Tracking'], ['zones', 'Shipping zones'], ['rates', 'Shipping rates']];

export function ShippingPage() {
    const { user } = useAuth(); const [params, setParams] = useSearchParams();
    const tab = params.get('view') || 'orders';
    if (!user?.can_manage_orders) return <Navigate to="/account" replace/>;
    return <div className="container page shipping-page"><div className="page-heading"><div><p className="eyebrow">Delivery management</p><h1>Shipping</h1><p>Prepare orders, manage delivery services, tracking, zones, and rates.</p></div></div><nav className="staff-order-tabs" aria-label="Shipping sections">{TABS.map(([value, label]) => <button key={value} type="button" className={tab === value ? 'active' : ''} onClick={() => setParams(value === 'orders' ? {} : { view: value })}>{label}</button>)}</nav>{(tab === 'orders' || tab === 'tracking') && <ShippingOrders trackingOnly={tab === 'tracking'}/>} {tab === 'methods' && <Methods/>}{tab === 'zones' && <Zones/>}{tab === 'rates' && <Rates/>}</div>;
}

function ShippingOrders({ trackingOnly }) {
    const [status, setStatus] = useState(trackingOnly ? 'shipped' : 'processing'); const [page, setPage] = useState(1); const [data, setData] = useState(null); const [error, setError] = useState('');
    useEffect(() => { setData(null); shippingApi.orders({ status, page }).then(setData).catch((reason) => setError(reason.message)); }, [page, status]);
    return <section><div className="shipping-toolbar"><label>Delivery status<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="processing">Ready to ship</option><option value="shipped">Shipped / in transit</option><option value="delivered">Delivered</option></select></label></div>{error ? <Alert>{error}</Alert> : !data ? <Loader/> : data.results.length ? <><div className="staff-product-table-wrap"><table className="staff-product-table"><thead><tr><th>Order</th><th>Customer</th><th>Destination</th><th>Courier</th><th>Tracking number</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.results.map((order) => <tr key={order.id}><th>{order.order_number}</th><td>{order.customer.username}</td><td>{order.city}, {order.country}</td><td>{order.courier || 'Not assigned'}</td><td>{order.tracking_number || 'Not assigned'}</td><td><span className={`status status--${order.status}`}>{order.status}</span></td><td><Link className="text-link" to={`/staff/orders/${order.id}`}>{order.status === 'processing' ? 'Prepare shipment' : 'View tracking'}</Link></td></tr>)}</tbody></table></div><Pagination page={page} count={data.count} onPage={setPage}/></> : <EmptyState title="No shipping orders">No orders match this delivery status.</EmptyState>}</section>;
}

function Methods() {
    const initial = { name: '', code: '', kind: 'standard', estimated_days: 3 }; const [form, setForm] = useState(initial);
    return <CrudSection title="Shipping methods" load={shippingApi.methods} create={() => shippingApi.createMethod({ ...form, estimated_days: Number(form.estimated_days) })} form={<div className="shipping-form"><input required placeholder="Method name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value, code: slug(e.target.value) })}/><select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })}><option value="standard">Standard</option><option value="express">Express</option><option value="pickup">Pickup</option></select><input type="number" min="0" aria-label="Estimated days" value={form.estimated_days} onChange={(e) => setForm({ ...form, estimated_days: e.target.value })}/></div>} columns={['Name', 'Type', 'Estimated delivery', 'Status']} render={(item) => [item.name, item.kind, `${item.estimated_days} days`, item.is_active ? 'Active' : 'Inactive']} remove={shippingApi.deleteMethod} toggle={(item) => shippingApi.updateMethod(item.id, { is_active: !item.is_active })}/>;
}
function Zones() {
    const [form, setForm] = useState({ name: '', countries: 'Ghana', regions: '', cities: '' });
    return <CrudSection title="Shipping zones" load={shippingApi.zones} create={() => shippingApi.createZone({ name: form.name, countries: split(form.countries), regions: split(form.regions), cities: split(form.cities) })} form={<div className="shipping-form"><input required placeholder="Zone name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/><input required placeholder="Countries, comma separated" value={form.countries} onChange={(e) => setForm({ ...form, countries: e.target.value })}/><input placeholder="Regions" value={form.regions} onChange={(e) => setForm({ ...form, regions: e.target.value })}/><input placeholder="Cities" value={form.cities} onChange={(e) => setForm({ ...form, cities: e.target.value })}/></div>} columns={['Zone', 'Countries', 'Regions', 'Cities']} render={(item) => [item.name, item.countries.join(', '), item.regions.join(', ') || 'All', item.cities.join(', ') || 'All']} remove={shippingApi.deleteZone} toggle={(item) => shippingApi.updateZone(item.id, { is_active: !item.is_active })}/>;
}
function Rates() {
    const [methods, setMethods] = useState([]); const [zones, setZones] = useState([]); const [form, setForm] = useState({ method: '', zone: '', amount: '0.00', free_shipping_threshold: '' });
    useEffect(() => { Promise.all([shippingApi.methods(), shippingApi.zones()]).then(([m, z]) => { setMethods(m.results || m); setZones(z.results || z); }); }, []);
    return <CrudSection title="Shipping rates" load={shippingApi.rates} create={() => shippingApi.createRate({ method: Number(form.method), zone: Number(form.zone), amount: form.amount, free_shipping_threshold: form.free_shipping_threshold || null })} form={<div className="shipping-form"><select required value={form.method} onChange={(e) => setForm({ ...form, method: e.target.value })}><option value="">Choose method</option>{methods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={form.zone} onChange={(e) => setForm({ ...form, zone: e.target.value })}><option value="">Choose zone</option>{zones.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required type="number" min="0" step="0.01" aria-label="Shipping amount" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })}/><input type="number" min="0" step="0.01" placeholder="Free above (optional)" value={form.free_shipping_threshold} onChange={(e) => setForm({ ...form, free_shipping_threshold: e.target.value })}/></div>} columns={['Method', 'Zone', 'Rate', 'Free shipping', 'Status']} render={(item) => [item.method_name, item.zone_name, formatPrice(item.amount), item.free_shipping_threshold ? formatPrice(item.free_shipping_threshold) : 'Never', item.is_active ? 'Active' : 'Inactive']} remove={shippingApi.deleteRate} toggle={(item) => shippingApi.updateRate(item.id, { is_active: !item.is_active })}/>;
}
function CrudSection({ title, load, create, form, columns, render, remove, toggle }) {
    const { notify } = useToast(); const [items, setItems] = useState(null); const [error, setError] = useState('');
    const refresh = useCallback(() => load().then((data) => setItems(data.results || data)).catch((reason) => setError(reason.message)), [load]); useEffect(() => { void refresh(); }, [refresh]);
    const submit = async (event) => { event.preventDefault(); setError(''); try { await create(); notify(`${title.slice(0, -1)} created.`, 'success'); await refresh(); } catch (reason) { setError(reason.message); } };
    const act = async (action, item) => { try { await action(item); await refresh(); } catch (reason) { setError(reason.message); } };
    return <section><div className="inventory-section-heading"><div><h2>{title}</h2><p>Configure the delivery options available to staff.</p></div></div>{error && <Alert>{error}</Alert>}<form className="shipping-create" onSubmit={submit}>{form}<Button type="submit">Add</Button></form>{!items ? <Loader/> : items.length ? <div className="staff-product-table-wrap"><table className="staff-product-table"><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}<th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}>{render(item).map((value, index) => index ? <td key={columns[index]}>{value}</td> : <th key={columns[index]}>{value}</th>)}<td><button className="text-link" type="button" onClick={() => void act(toggle, item)}>Toggle</button> <button className="danger-link" type="button" onClick={() => void act(() => remove(item.id), item)}>Delete</button></td></tr>)}</tbody></table></div> : <EmptyState title={`No ${title.toLowerCase()}`}>Add the first configuration above.</EmptyState>}</section>;
}
const split = (value) => value.split(',').map((item) => item.trim()).filter(Boolean);
const slug = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
