# Generated by Django 6.0.7 on 2026-08-12 05:08

import invoices.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=invoices.storage.private_invoice_storage, upload_to='%Y/%m/'),
        ),
    ]
